set_project("bsp-gd32e10x")

target("bsp_gd32e10x")
    set_kind("static")
    add_defines("GD32E103V_EVAL")
    add_includedirs("drivers")
    add_includedirs("Library/CMSIS")
    add_includedirs("Library/CMSIS/GD/GD32E10x/Include")
    add_includedirs("Library/GD32E10x_standard_peripheral/Include")
    add_files("main.c")
    add_files("drivers/*.c")
    add_files("Library/GD32E10x_standard_peripheral/Source/*.c")
    add_files("Library/CMSIS/GD/GD32E10x/Source/system_gd32e10x.c")
    add_files("startup/gcc/startup_gd32e10x.s")
